[package]
name = "detrustpay"
version = "2.0.0"
description = "DeTrustPay Solana conditional payment program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "detrustpay"

[features]
default = []
anchor-debug = []
custom-heap = []
custom-panic = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-lang = {version="0.32.1", features=["init-if-needed"]}
anchor-spl = "0.32.1"
solana-sha256-hasher = "2.3.0"
