[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
detrustpay = "3QE69X6FsKxaop5osBW1WL11cCTMMvDuXJLZ9s2TcCNy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"
